// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "floppy_dump_window.h"

floppy_dump_window::floppy_dump_window() {
  { window = new Fl_Double_Window(474, 427, "Floppy disk dump");
    window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(5, 5, 155, 180, "Dump setting");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      { number_of_track = new Fl_Value_Input(115, 90, 35, 25, "Number of tracks");
        number_of_track->labelsize(12);
        number_of_track->textsize(12);
      } // Fl_Value_Input* number_of_track
      { number_of_retry = new Fl_Value_Input(115, 155, 35, 25, "Retry");
        number_of_retry->labelsize(12);
        number_of_retry->textsize(12);
      } // Fl_Value_Input* number_of_retry
      o->end();
    } // Fl_Group* o
    { sel_drive_a = new Fl_Round_Button(15, 25, 80, 16, "Drive A:");
      sel_drive_a->type(102);
      sel_drive_a->down_box(FL_ROUND_DOWN_BOX);
    } // Fl_Round_Button* sel_drive_a
    { sel_drive_b = new Fl_Round_Button(15, 45, 80, 16, "Drive B:");
      sel_drive_b->type(102);
      sel_drive_b->down_box(FL_ROUND_DOWN_BOX);
    } // Fl_Round_Button* sel_drive_b
    { double_sided = new Fl_Check_Button(15, 65, 110, 16, "Double sided");
      double_sided->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* double_sided
    { double_step = new Fl_Check_Button(15, 125, 100, 16, "Double step");
      double_step->down_box(FL_DOWN_BOX);
    } // Fl_Check_Button* double_step
    { Fl_Group* o = new Fl_Group(165, 5, 305, 90, "Status");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      { global_status = new Fl_Output(175, 25, 280, 25);
        global_status->labelsize(12);
        global_status->textsize(12);
      } // Fl_Output* global_status
      { current_status = new Fl_Output(175, 55, 280, 25);
        current_status->labelsize(12);
        current_status->textsize(12);
      } // Fl_Output* current_status
      o->end();
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(215, 130, 80, 25, "OK");
      o->callback((Fl_Callback*)floppy_dump_ok, (void*)(this));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(315, 130, 80, 25, "Read Disk");
      o->callback((Fl_Callback*)floppy_dump_window_bt_read, (void*)(this));
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(5, 190, 465, 230, "Floppy Map");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
      o->end();
    } // Fl_Group* o
    window->end();
  } // Fl_Double_Window* window
}
