// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef floppy_dump_window_h
#define floppy_dump_window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>
extern void floppy_dump_stop(Fl_Button*, void*);
extern void floppy_dump_window_bt_read(Fl_Button*, void*);

class floppy_dump_window {
public:
  floppy_dump_window();
  Fl_Double_Window *window;
  Fl_Round_Button *sel_drive_a;
  Fl_Round_Button *sel_drive_b;
  Fl_Output *global_status;
  Fl_Output *current_status;
  Fl_Box *layout_area;
  Fl_Value_Input *start_track;
  Fl_Value_Input *end_track;
  Fl_Check_Button *side_0;
  Fl_Check_Button *side_1;
  Fl_Check_Button *double_step;
  Fl_Check_Button *FM125;
  Fl_Check_Button *FM150;
  Fl_Check_Button *FM250;
  Fl_Check_Button *MFM250;
  Fl_Check_Button *MFM500;
  Fl_Check_Button *MFM1000;
  Fl_Check_Button *FM500;
  Fl_Check_Button *MFM300;
  Fl_Value_Input *number_of_retry;
};
#endif
