#define FILE_VERSION        1,5,2,0
#define STR_FILE_VERSION   "1,5,2,0\0"
#define STR_FILE_VERSION2  "1.5.2.0"
#define STR_DATE           "11/01/2011\0"
#define NOMFENETRE    "HxCFloppyEmulator "##STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
