// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef filesystem_generator_window_h
#define filesystem_generator_window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern void filesystem_generator_window_bt_injectdir(Fl_Button*, void*);
#include <FL/Fl_Choice.H>
extern void filesystem_generator_window_bt_selectdir(Fl_Button*, void*);
#include <FL/Fl_Input.H>
#include <FL/Fl_Tree.H>
extern void filesystem_generator_window_browser_fs(Fl_Tree*, void*);
#include <FL/Fl_Text_Display.H>
extern void filesystem_generator_window_bt_delete(Fl_Button*, void*);
extern void filesystem_generator_window_bt_getfiles(Fl_Button*, void*);
extern void filesystem_generator_window_bt_putfiles(Fl_Button*, void*);
extern void filesystem_generator_window_bt_createdir(Fl_Button*, void*);

class filesystem_generator_window {
public:
  filesystem_generator_window();
  Fl_Double_Window *window;
  Fl_Button *bt_injectdir;
  Fl_Button *bt_cancel;
private:
  inline void cb_bt_cancel_i(Fl_Button*, void*);
  static void cb_bt_cancel(Fl_Button*, void*);
public:
  Fl_Choice *choice_filesystype;
  Fl_Tree *fs_browser;
  Fl_Text_Display *txtout_freesize;
  Fl_Button *bt_delete;
  Fl_Button *bt_get;
  Fl_Button *bt_put;
  Fl_Button *bt_createdir;
};
#endif
