// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "floppy_infos_window.h"

extern "C"
{
	#include "libhxcfe.h"
	#include "usb_hxcfloppyemulator.h"
	#include "os_api.h"
}

#include "cb_floppy_infos_window.h"
#include "fl_mouse_box.h"

floppy_infos_window::floppy_infos_window() {
  { window = new Fl_Double_Window(1003, 670, "Visual Floppy disk");
    window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 502, 250, 166, "Track");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(12);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      { track_number_slide = new Fl_Value_Slider(16, 537, 220, 19, "Track number");
        track_number_slide->type(1);
        track_number_slide->textsize(14);
        track_number_slide->callback((Fl_Callback*)disk_infos_window_callback, (void*)(this));
      } // Fl_Value_Slider* track_number_slide
      { side_number_slide = new Fl_Value_Slider(15, 597, 220, 19, "Side number");
        side_number_slide->type(1);
        side_number_slide->textsize(14);
        side_number_slide->callback((Fl_Callback*)disk_infos_window_callback, (void*)(this));
      } // Fl_Value_Slider* side_number_slide
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(570, 502, 394, 166, "Status");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      { x_pos = new Fl_Output(580, 523, 180, 25);
        x_pos->labelsize(12);
        x_pos->textsize(12);
      } // Fl_Output* x_pos
      { y_pos = new Fl_Output(760, 523, 194, 25);
        y_pos->labelsize(12);
        y_pos->textsize(12);
      } // Fl_Output* y_pos
      { object_txt = new Fl_Output(580, 574, 374, 87);
        object_txt->labelsize(12);
        object_txt->textsize(12);
      } // Fl_Output* object_txt
      { global_status = new Fl_Output(580, 549, 374, 24);
        global_status->labelsize(12);
        global_status->textsize(12);
      } // Fl_Output* global_status
      o->end();
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(969, 504, 30, 163, "OK");
      o->callback((Fl_Callback*)floppy_infos_ok, (void*)(this));
    } // Fl_Button* o
    { floppy_map_disp = new Fl_Group(0, 1, 1000, 500, "Floppy Map");
      floppy_map_disp->box(FL_ENGRAVED_FRAME);
      floppy_map_disp->labeltype(FL_EMBOSSED_LABEL);
      floppy_map_disp->labelsize(12);
      floppy_map_disp->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      floppy_map_disp->end();
    } // Fl_Group* floppy_map_disp
    { Fl_Group* o = new Fl_Group(253, 502, 314, 167, "View");
      o->box(FL_ENGRAVED_FRAME);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(12);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      { x_time = new Fl_Value_Slider(263, 522, 292, 20, "x time scale");
        x_time->type(5);
        x_time->textsize(14);
        x_time->callback((Fl_Callback*)disk_infos_window_callback, (void*)(this));
      } // Fl_Value_Slider* x_time
      { y_time = new Fl_Value_Slider(263, 557, 292, 20, "y time scale");
        y_time->type(5);
        y_time->textsize(14);
        y_time->callback((Fl_Callback*)disk_infos_window_callback, (void*)(this));
      } // Fl_Value_Slider* y_time
      { x_offset = new Fl_Value_Slider(263, 595, 292, 20, "x offset");
        x_offset->type(5);
        x_offset->textsize(14);
        x_offset->callback((Fl_Callback*)disk_infos_window_callback, (void*)(this));
      } // Fl_Value_Slider* x_offset
      { track_view_bt = new Fl_Round_Button(302, 640, 64, 15, "Track view");
        track_view_bt->type(102);
        track_view_bt->down_box(FL_ROUND_DOWN_BOX);
        track_view_bt->callback((Fl_Callback*)disk_infos_window_callback, (void*)(this));
      } // Fl_Round_Button* track_view_bt
      { disc_view_bt = new Fl_Round_Button(443, 640, 64, 15, "disk view");
        disc_view_bt->type(102);
        disc_view_bt->down_box(FL_ROUND_DOWN_BOX);
        disc_view_bt->callback((Fl_Callback*)disk_infos_window_callback, (void*)(this));
      } // Fl_Round_Button* disc_view_bt
      o->end();
    } // Fl_Group* o

	Fl_Mouse_Box *m = new Fl_Mouse_Box(floppy_map_disp->x(), floppy_map_disp->y(),floppy_map_disp->w(), floppy_map_disp->h(), 0);
	m->callback(mouse_di_cb);

    window->end();
  } // Fl_Double_Window* window
}
