#define FILE_VERSION        2,0,10,2
#define STR_FILE_VERSION   "2,0,10,2\0"
#define STR_FILE_VERSION2  "2.0.10.2"
#define STR_DATE           "02/18/2013\0"
#define NOMFENETRE    "HxCFloppyEmulator v"STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
