int init_caps_lib(HXCFE* hxcfe);


#ifdef WIN32
#define CALLCONV __cdecl
#else
#define CALLCONV 
#endif

typedef SDWORD (CALLCONV* CAPSINIT)(void);
typedef SDWORD (CALLCONV* CAPSADDIMAGE)(void);
typedef SDWORD (CALLCONV* CAPSLOCKIMAGE)(SDWORD,PUBYTE);
typedef SDWORD (CALLCONV* CAPSLOCKIMAGEMEMORY)(SDWORD,PUBYTE,UDWORD,UDWORD);
typedef SDWORD (CALLCONV* CAPSGETIMAGETYPEMEMORY)(PUBYTE,UDWORD);
typedef SDWORD (CALLCONV* CAPSUNLOCKIMAGE)(SDWORD);
typedef SDWORD (CALLCONV* CAPSLOADIMAGE)(SDWORD,UDWORD);
typedef SDWORD (CALLCONV* CAPSGETIMAGEINFO)(PCAPSIMAGEINFO,SDWORD);
typedef SDWORD (CALLCONV* CAPSLOCKTRACK)(PCAPSTRACKINFO,SDWORD,UDWORD,UDWORD,UDWORD);
typedef SDWORD (CALLCONV* CAPSUNLOCKTRACK)(SDWORD id, UDWORD cylinder, UDWORD head);
typedef SDWORD (CALLCONV* CAPSUNLOCKALLTRACKS)(SDWORD);
typedef SDWORD (CALLCONV* CAPSGETVERSIONINFO)(PCAPSVERSIONINFO,UDWORD);
typedef SDWORD (CALLCONV* CAPSREMIMAGE)(SDWORD id);

extern CAPSINIT pCAPSInit;
extern CAPSADDIMAGE pCAPSAddImage;
extern CAPSLOCKIMAGE pCAPSLockImage;
extern CAPSGETIMAGETYPEMEMORY pCAPSGetImageTypeMemory;
extern CAPSLOCKIMAGEMEMORY pCAPSLockImageMemory;
extern CAPSUNLOCKIMAGE pCAPSUnlockImage;
extern CAPSLOADIMAGE pCAPSLoadImage;
extern CAPSGETIMAGEINFO pCAPSGetImageInfo;
extern CAPSLOCKTRACK pCAPSLockTrack;
extern CAPSUNLOCKTRACK pCAPSUnlockTrack;
extern CAPSUNLOCKALLTRACKS pCAPSUnlockAllTracks;
extern CAPSGETVERSIONINFO pCAPSGetVersionInfo;
extern CAPSREMIMAGE pCAPSRemImage;
