// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "batch_converter_window.h"

void batch_converter_window::cb_bt_cancel_i(Fl_Button* o, void*) {
  ((Fl_Window*)(o->parent()))->hide();
}
void batch_converter_window::cb_bt_cancel(Fl_Button* o, void* v) {
  ((batch_converter_window*)(o->parent()->user_data()))->cb_bt_cancel_i(o,v);
}

batch_converter_window::batch_converter_window() {
  { window = new Fl_Double_Window(413, 244);
    window->user_data((void*)(this));
    { choice_file_format = new Fl_Choice(19, 26, 271, 23, "Target file format :");
      choice_file_format->down_box(FL_BORDER_BOX);
      choice_file_format->labelsize(12);
      choice_file_format->textsize(12);
      choice_file_format->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Choice* choice_file_format
    { strin_src_dir = new Fl_Input(19, 70, 271, 25, "Source directory");
      strin_src_dir->labelsize(12);
      strin_src_dir->textsize(12);
      strin_src_dir->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Input* strin_src_dir
    { strin_dst_dir = new Fl_Input(19, 126, 271, 24, "Target directory");
      strin_dst_dir->labelsize(12);
      strin_dst_dir->textsize(12);
      strin_dst_dir->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Input* strin_dst_dir
    { strout_convert_status = new Fl_Output(19, 171, 376, 30);
      strout_convert_status->box(FL_PLASTIC_UP_BOX);
      strout_convert_status->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Output* strout_convert_status
    { bt_select_src = new Fl_Button(305, 70, 90, 25, "Select");
    } // Fl_Button* bt_select_src
    { bt_select_dst = new Fl_Button(305, 127, 90, 25, "Select");
    } // Fl_Button* bt_select_dst
    { bt_convert = new Fl_Button(155, 210, 105, 25, "Convert");
    } // Fl_Button* bt_convert
    { bt_cancel = new Fl_Button(290, 210, 105, 25, "Cancel");
      bt_cancel->callback((Fl_Callback*)cb_bt_cancel);
    } // Fl_Button* bt_cancel
    window->end();
  } // Fl_Double_Window* window
}
