// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "filesystem_generator_window.h"

void filesystem_generator_window::cb_bt_cancel_i(Fl_Button* o, void*) {
  ((Fl_Window*)(o->parent()))->hide();
}
void filesystem_generator_window::cb_bt_cancel(Fl_Button* o, void* v) {
  ((filesystem_generator_window*)(o->parent()->user_data()))->cb_bt_cancel_i(o,v);
}

filesystem_generator_window::filesystem_generator_window() {
  { window = new Fl_Double_Window(352, 73, "Create a File System based floppy");
    window->user_data((void*)(this));
    { bt_injectdir = new Fl_Button(255, 10, 90, 25, "Inject directory");
      bt_injectdir->labelsize(12);
    } // Fl_Button* bt_injectdir
    { bt_cancel = new Fl_Button(255, 40, 90, 25, "Cancel");
      bt_cancel->labelsize(12);
      bt_cancel->callback((Fl_Callback*)cb_bt_cancel);
    } // Fl_Button* bt_cancel
    { choice_filesystype = new Fl_Choice(5, 25, 240, 25, "File system type :");
      choice_filesystype->down_box(FL_BORDER_BOX);
      choice_filesystype->labelsize(12);
      choice_filesystype->textsize(12);
      choice_filesystype->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Choice* choice_filesystype
    window->end();
  } // Fl_Double_Window* window
}
