/*
//
// Copyright (C) 2006-2014 Jean-François DEL NERO
//
// This file is part of the HxCFloppyEmulator library
//
// HxCFloppyEmulator may be used and distributed without restriction provided
// that this copyright statement is not removed from the file and that any
// derivative work contains the original copyright notice and the associated
// disclaimer.
//
// HxCFloppyEmulator is free software; you can redistribute it
// and/or modify  it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// HxCFloppyEmulator is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//   See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with HxCFloppyEmulator; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//
*/
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include "libhxcfe.h"

#include "xml_loader.h"

#include "tracks/sector_extractor.h"

#include "libhxcadaptor.h"

int XML_libWrite_DiskFile(HXCFLOPPYEMULATOR* floppycontext,FLOPPY * floppy,char * filename)
{
	int i,j,s;
	FILE * xmlfile;
	int fileoffset,nb_sectorfound;
	SECTORSEARCH* ss;
	SECTORCONFIG** sca;

	floppycontext->hxc_printf(MSG_INFO_1,"Write XML file %s...",filename);

	fileoffset = 0;

	xmlfile=hxc_fopen(filename,"wb");
	if(xmlfile)
	{
		fprintf(xmlfile,"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n");
		fprintf(xmlfile,"<!-- HxC Floppy Emulator Disk Layout -->\n");

		fprintf(xmlfile,"<disk_layout>\n");

		fprintf(xmlfile,"\t<disk_layout_name>AUTOGENERATEDLAYOUT</disk_layout_name>\n");
		fprintf(xmlfile,"\t<disk_layout_description>Auto Generated Disk Layout</disk_layout_description>\n");
		fprintf(xmlfile,"\t<prefered_file_extension>img</prefered_file_extension>\n");
		fprintf(xmlfile,"\t<interface_mode>GENERIC_SHUGART_DD_FLOPPYMODE</interface_mode>\n");

		fprintf(xmlfile,"\t<file_size>%d</file_size>\n",hxcfe_getFloppySize(floppycontext,floppy,0));

		fprintf(xmlfile,"\t<layout>\n");

		fprintf(xmlfile,"\t\t<number_of_track>%d</number_of_track>\n",floppy->floppyNumberOfTrack);
		fprintf(xmlfile,"\t\t<number_of_side>%d</number_of_side>\n",floppy->floppyNumberOfSide);

		fprintf(xmlfile,"\t\t<format>ISO_MFM</format>\n",floppy->floppyNumberOfSide);

		fprintf(xmlfile,"\t\t<start_sector_id>%d</start_sector_id>\n",0);
		fprintf(xmlfile,"\t\t<sector_per_track>%d</sector_per_track>\n",6);

		fprintf(xmlfile,"\t\t<sector_size>%d</sector_size>\n",1024);

		fprintf(xmlfile,"\t\t<interleave>%d</interleave>\n",1);

		fprintf(xmlfile,"\t\t<skew_per_side>%d</skew_per_side>\n",0);

		fprintf(xmlfile,"\t\t<skew_per_track>%d</skew_per_track>\n",0);
		fprintf(xmlfile,"\t\t<formatvalue>%d</formatvalue>\n",0x00);

		fprintf(xmlfile,"\t\t<gap3>%d</gap3>\n",0x30);

		fprintf(xmlfile,"\t\t<bitrate>%d</bitrate>\n",floppy->floppyBitRate);
		fprintf(xmlfile,"\t\t<pregap>%d</pregap>\n",0);
		fprintf(xmlfile,"\t\t<rpm>%d</rpm>\n",300);

		fprintf(xmlfile,"\t\t<track_list>\n");


		ss=hxcfe_initSectorSearch(floppycontext,floppy);
		if(ss)
		{
			for(j=0;j<80;j++)
			{
				for(i=0;i<2;i++)
				{
					fprintf(xmlfile,"\t\t\t<track track_number=\"%.2d\" side_number=\"%d\">",j,i);
					fprintf(xmlfile,"<data_offset>0x%.6X</data_offset>",fileoffset);

					fprintf(xmlfile,"<sector_list>");

					sca = hxcfe_getAllTrackISOSectors(ss,j,i,&nb_sectorfound);

					for(s=0;s<nb_sectorfound;s++)
					{
						fprintf(xmlfile,"<sector sector_id=\"%d\" sector_size=\"%d\">",sca[s]->sector,sca[s]->sectorsize);
						fprintf(xmlfile,"</sector>");

						fileoffset += sca[s]->sectorsize;

						hxcfe_freeSectorConfig  (ss,sca[s]);
					}

					free(sca);

					fprintf(xmlfile,"</sector_list>");

					fprintf(xmlfile,"</track>\n");
				}
			}
			hxcfe_deinitSectorSearch(ss);
		}

		fprintf(xmlfile,"\t\t</track_list>\n");
		fprintf(xmlfile,"\t</layout>\n");
		fprintf(xmlfile,"</disk_layout>\n");

		hxc_fclose(xmlfile);
	}

	return 0;
}
