#define FILE_VERSION        2,0,12,1
#define STR_FILE_VERSION   "2,0,12,1\0"
#define STR_FILE_VERSION2  "2.0.12.1"
#define STR_DATE           "03/21/2013\0"
#define NOMFENETRE    "HxCFloppyEmulator v"STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
