..\..\converttools\bmptoh DiskLayout_ABB_ASEA_640KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_ABB_ASEA_320KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_ABB_ASEA_328KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Acorn_160K_ADFS.xml -DATA
..\..\converttools\bmptoh DiskLayout_Acorn_320K_ADFM.xml -DATA
..\..\converttools\bmptoh DiskLayout_Acorn_640K_ADFL.xml -DATA
..\..\converttools\bmptoh DiskLayout_AED6200P.xml -DATA
..\..\converttools\bmptoh DiskLayout_AkaiS950_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AkaiS950_HD_1_6MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AkaiS3000_HD_1_6MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AmstradCPC_DD.xml -DATA
..\..\converttools\bmptoh DiskLayout_AtariST_DD_720KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Automatix_RAIL_DD_400KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_CasioFZ1_HD_1_25MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_COMX_35_DS_140KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_COMX_35_SS_70KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_COMX_35_SS_140KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DEC_RX55.xml -DATA
..\..\converttools\bmptoh DiskLayout_Didaktik_Spectrum_DD_720KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_DD_720KB.xml   -DATA
..\..\converttools\bmptoh DiskLayout_DOS_HD_1_44MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_ED_2_88MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_EXHD_6_78MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_EXHD_4_5MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_EXDD_2_5MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Dynacord_AddOne.xml -DATA
..\..\converttools\bmptoh DiskLayout_Dynacord_HD_1600KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Emax_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Emax_II_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Ensoniq_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Ensoniq_HD_1600KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Ensoniq_Mirage_440KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Excellon_CNC6.xml -DATA
..\..\converttools\bmptoh DiskLayout_GeneralMusic_GEM_S3_1600KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_GeneralMusic_GEM_WX_Expander.xml -DATA
..\..\converttools\bmptoh DiskLayout_Gravograph_ISIS_640KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_KorgDSS1_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_KorgT3_HD_1_6MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_LIF_3_50_264KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_LIF_3_50_616KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_LIF_3_50_1232KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_LIF_5_25_264KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_LinnForat9K_720KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Microtan_65_TANDOS.xml -DATA
..\..\converttools\bmptoh DiskLayout_Memotech_40T.xml -DATA
..\..\converttools\bmptoh DiskLayout_Memotech_80T.xml -DATA
..\..\converttools\bmptoh DiskLayout_OpusDiscovery.xml -DATA
..\..\converttools\bmptoh DiskLayout_Oerlikon_Balzers_250KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Oric_Jasmin_357KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_OS9_640KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_OS9_1280KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_PUMA_Robot_640KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Roland_W30_S330_W50_S50_S550_DD_720KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Tatung_Einstein_DD_200KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Tatung_Einstein_DD_400KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Timex_FDD3000_40T1S.xml -DATA
..\..\converttools\bmptoh DiskLayout_Timex_FDD3000_80T2S.xml -DATA
..\..\converttools\bmptoh DiskLayout_TRS80_JV1.xml -DATA
..\..\converttools\bmptoh DiskLayout_UKNC_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Unitel_Videotex.xml -DATA


move *.h ..

