..\..\converttools\bmptoh DiskLayout_DOS_DD_720KB.xml   -DATA
..\..\converttools\bmptoh DiskLayout_DOS_HD_1_44MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_CasioFZ1_HD_1_25MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AkaiS950_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AkaiS950_HD_1_6MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AkaiS3000_HD_1_6MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AmstradCPC_DD.xml -DATA
..\..\converttools\bmptoh DiskLayout_Ensoniq_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Ensoniq_HD_1600KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_ED_2_88MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_EXHD_6_78MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_EXHD_4_5MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_DOS_EXDD_2_5MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Roland_W30_S330_W50_S50_S550_DD_720KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_LinnForat9K_720KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_KorgT3_HD_1_6MB.xml -DATA
..\..\converttools\bmptoh DiskLayout_AtariST_DD_720KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_OS9_1280KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_GeneralMusic_GEM_S3_1600KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_GeneralMusic_GEM_WX_Expander.xml -DATA
..\..\converttools\bmptoh DiskLayout_Emax_DD_800KB.xml -DATA
..\..\converttools\bmptoh DiskLayout_Ensoniq_Mirage_440KB.xml -DATA

move *.h ..
