#define FILE_VERSION        1,6,5,1
#define STR_FILE_VERSION   "1,6,5,1b\0"
#define STR_FILE_VERSION2  "1.6.5.1b"
#define STR_DATE           "23/04/2011\0"
#define NOMFENETRE    "HxCFloppyEmulator "##STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
