#define FILE_VERSION        1,6,11,5a
#define STR_FILE_VERSION   "1,6,11,5a\0"
#define STR_FILE_VERSION2  "1.6.11.5a"
#define STR_DATE           "27/08/2011\0"
#define NOMFENETRE    "HxCFloppyEmulator "##STR_FILE_VERSION2

#define FILEVER        FILE_VERSION
#define PRODUCTVER     FILE_VERSION
#define STRFILEVER     STR_FILE_VERSION
#define STRPRODUCTVER  STR_FILE_VERSION
