//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource_HxCFloppyEmu.RC
//
#define IDSAVE                          2
#define IDLOAD                          3
#define IDSAVECONFIG                    3
#define IDLOADCONFIG                    4
#define ID_MAKEEMPTYFLOPPY              5
#define IDSAVE_HXCFECFG                 5
#define IDLOAD_HXCFECFG                 6
#define IDD_OLE_PROPPAGE_LARGE          105
#define ID_DIALOG_PAGE_PRINCIPALE       105
#define ID_DIALOG_ABOUT                 111
#define IDB_BITMAP1                     113
#define IDB_BITMAP2                     115
#define IDB_BITMAP3                     118
#define IDI_ICON2                       120
#define IDR_MENU1                       129
#define IDD_DIALOG_STATS                133
#define IDB_BITMAP4                     133
#define IDD_DIALOG_CONFIG               134
#define IDC_CURSOR1                     135
#define ID_DIALOG_LOGS                  135
#define IDD_RAWFILECONFIG               137
#define ID_DIALOG_LICENSE               138
#define IDD_CREATEFILESYSTEM            139
#define IDD_BATCHCONVERT                140
#define IDD_DIALOG_MAINDIALOG           141
#define IDD_DIALOG_SDHXCFECONFIG        142
#define IDD_DIALOG_FLOPPYDUMP           142
#define IDB_BITMAP5                     147
#define IDB_BITMAP6                     152
#define IDB_BITMAP7                     153
#define ID_OK                           1049
#define IDC_BUTTON1                     1058
#define IDC_SLIDER1                     1059
#define IDC_BUTTONLICENSE               1059
#define IDC_BUTTON_CREATEFLOPPY         1059
#define IDC_MAXSETTLE                   1060
#define IDC_BUTTON_EXPORT               1060
#define IDC_RELEASENOTES                1060
#define IDC_MINSETTLE                   1061
#define IDC_BUTTON_LOADRAW              1061
#define IDC_PACKETSIZE                  1062
#define IDC_BUTTON_CONVERT              1062
#define IDC_PRIORITYSLIDER              1063
#define IDC_BUTTON_SETTINGS             1063
#define IDC_BUTTON_SDCONFIG             1063
#define IDC_DATASENT                    1064
#define IDC_BUTTON_USBCONFIG            1064
#define IDC_DATATHROUGHPUT              1065
#define IDC_BUTTON_FLOPPYDUMP           1065
#define IDC_NBOFPACKET                  1066
#define IDC_NBOFSYNCLOST                1067
#define IDC_BUTTON_RESET                1068
#define IDC_RADIO1                      1069
#define IDC_USBHXCFE_STATUS             1069
#define IDC_RADIO2                      1070
#define IDC_RADIO3                      1071
#define IDC_RADIO4                      1072
#define IDC_CHECK1                      1074
#define IDC_AUTO                        1074
#define IDC_SIDE0ENABLE                 1074
#define IDC_RADIO_DS0                   1074
#define IDC_CHECK2                      1075
#define IDC_DISABLE                     1075
#define IDC_SIDE1ENABLE                 1075
#define IDC_CHECK3                      1076
#define IDC_TWISTED                     1076
#define IDC_SIDE0FIRST                  1076
#define IDC_COMBO1                      1077
#define IDC_REVERSESIDE                 1077
#define IDC_AUTO_USB                    1077
#define IDC_INTERSIDESECTORNUMBERING    1077
#define IDC_TRACKTYPE                   1078
#define IDC_DOUBLESTEP                  1078
#define IDC_COMBO_USBIFMODE             1078
#define ID_CLOSE                        1079
#define IDC_DOUBLESTEP_USB              1079
#define IDC_AUTAGAP3                    1079
#define IDC_LOGS                        1080
#define IDC_REVERSESIDE2                1080
#define ID_SETLOGFILE                   1081
#define IDC_NUMBEROFTRACK               1081
#define IDC_NBOFSECTORS                 1082
#define IDC_TOTALSIZE                   1083
#define IDC_RPM                         1084
#define IDC_BITRATE                     1085
#define IDC_GAP3LEN                     1086
#define IDLOADRAWFILE                   1087
#define IDC_SECTORSIZE                  1088
#define IDC_SECTORPERTRACK              1089
#define IDCANCELRAWFILE                 1090
#define IDC_INTERLEAVE                  1091
#define IDC_LICENSE                     1091
#define IDSELECTSOURCEDIR               1091
#define IDC_FSTYPE                      1092
#define IDSELECTDESTINATIONDIR          1092
#define IDC_SECTORIDSTART               1092
#define IDBUILDFS                       1093
#define IDC_SKEW                        1093
#define IDC_FFTYPE                      1094
#define IDC_FORMATVALUE                 1094
#define IDC_SOURCEDIR                   1095
#define IDC_SIDESKEW                    1095
#define IDC_DESTDIR                     1096
#define IDBATCHCONV                     1097
#define IDC_CONVERTSTATUS               1098
#define IDC_EDIT_TRACKPOS               1099
#define IDC_EDIT_STATUS                 1101
#define IDC_SLIDER_TRACKPOS             1102
#define IDC_BUTTON_LOAD                 1103
#define IDC_AUDIO_STEP                  1104
#define IDC_AUDIO_UI                    1105
#define IDC_SLIDER_LCDBACKLIGHT         1106
#define IDC_SLIDER_STANDBY              1107
#define IDC_DISABLE_DISKB_SELECTOR      1108
#define IDC_EDIT1                       1109
#define IDC_EDIT2                       1110
#define IDC_RADIO_DS1                   1110
#define IDC_SLIDER_STEP_SOUND           1111
#define IDC_RADIO_DS2                   1111
#define IDC_RADIO_DS3                   1112
#define IDC_AUTOBOOTMODE                1112
#define IDC_LOADLASTFLOPPY              1113
#define IDC_STATIC_MAIN01               1113
#define IDC_STATIC_MAIN02               1114
#define IDC_SLIDER_UI_SOUND             1114
#define IDC_STATIC_MAIN03               1115
#define IDC_AUTOBOOTPWRUP               1115
#define IDC_STATIC_MAIN04               1116
#define IDC_STARTUPAPWRUP               1116
#define IDC_STATIC_MAIN05               1117
#define IDC_STARTUPBPWRUP               1117
#define IDC_SLIDER_SCROLLTXTSPEED       1118
#define IDC_STATIC_MAIN06               1118
#define IDC_STATIC_MAIN07               1119
#define IDC_AUTOBOOTMODEINDEXPREINC     1119
#define IDC_STATIC_MAIN08               1120
#define IDLOAD_READDISK                 1120
#define IDC_DOUBLESTEP_DUMP             1121
#define IDC_NUMBEROFTRACK_DUMP          1122
#define IDC_DOUBLESIDE_DUMP             1123
#define ID_DRIVE_DS0                    40028
#define ID_DRIVE_DS1                    40029
#define ID_DRIVE_DS2                    40030
#define ID_DRIVE_MTRON                  40031
#define ID_DRIVE_DISABLE                40032
#define ID_ABOUT_HXCFLOPPYEMULATOR      40036
#define ID_WRITEMFM_FILE                40037
#define ID_DRIVE_IBMPCMODE              40041
#define ID_DRIVE_SHUGARTMODE            40043
#define ID_DISK_WRITESDCARD             40044
#define ID_DISK_SDCARDSTDALONE          40044
#define ID_INFOS_USBSTATS               40045
#define ID_INFOS_SETLOGFILE             40046
#define ID_DRIVE_SETTINGS               40047
#define ID_WRITEAFI_FILE                40048
#define ID_WRITERAW_FILE                40049
#define ID_LOAD_LOAD                    40050
#define ID_IMAGES_LOADRAWFILE           40051
#define ID_WRITEVTRUCCO_FILE            40052
#define ID_IMAGES_CREATEFILESYSTEM      40053
#define ID_IMAGES_CONVERT               40054
#define ID_DISK_EXPORT                  40055
#define ID_DRIVE_SDHXCFECFGFILE         40056
#define ID_FLOPPYIMAGE_DUMPAFLOPPYDISK  40057
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         40058
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
